disableStartupPopups: true
notARepository: prompt

gui:
  nerdFontsVersion: "3"
  showFileTree: false
  skipRewordInEditorWarning: true

  theme:
    selectedLineBgColor:
      - "#26464a"

os:
  edit: 'nvim --server /tmp/nvim-server.pipe --remote-tab "{{filename}}"'
  editAtLine: 'nvim +{{line}} --server /tmp/nvim-server.pipe --remote-tab "{{filename}}"'
  openDirInEditor: 'nvim --server /tmp/nvim-server.pipe --remote-tab "{{dir}}"'

git:
  parseEmoji: true
