disableStartupPopups: true
notARepository: prompt

gui:
  nerdFontsVersion: "3"
  showFileTree: false
  skipRewordInEditorWarning: true

  theme:
    selectedLineBgColor:
      - "#26464a"

os:
  editPreset: "nvim"

git:
  parseEmoji: true
